name: Deploy Node.js to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies (optional local build)
        run: npm ci

      - name: Run tests (if any)
        run: npm test || echo "No tests found"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/node-1 || exit 1
            git fetch origin
            git reset --hard origin/main
            npm ci
            pm2 reload node-1 || pm2 start app.js --name node-1



