name: Deploy Node App to EC2
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup SSH key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
        chmod 600 key.pem
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          pm2 stop node-hello || true
          rm -rf node-hello
          git clone https://github.com/<your-username>/node-hello.git
          cd node-hello
          npm install
          pm2 start app.js --name node-hello
          pm2 save
        EOF
