name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Start app in background
      run: |
        node app.js > output.log 2>&1 &
        echo $! > pid.txt
        sleep 5
        echo "App started. Checking output..."
        cat output.log

    - name: Stop app
      run: |
        kill $(cat pid.txt)
        echo "App stopped."

    - name: Done
      run: echo "✅ Application ran successfully in CI."

